### PR TITLE
Update testcontainers to 1.15.2 for branch 3.9

### PR DESCRIPTION
**Pull request by DavideD**
Similar to https://github.com/eclipse-vertx/vertx-sql-client/pull/890

### CODE REVIEW

**Review by tsegismont — APPROVED** [review]
Thank you @DavideD !

**Comment by vietj** [comment]
An eclipse CQ must be filed before merging this dependency.

**Comment by DavideD** [comment]
Sorry, what's an eclipse CQ?

**Comment by vietj** [comment]
it is paperwork for dependnecies for eclipse project @DavideD

**Pull request merged**
