### PR TITLE
Add Postgres resultset metadata and column metadata support

### LINKED ISSUE #470: [Postgres]Provide access to resultset metadata
Please make enum `DataType` and `PgColumnDesc` public (package `io.vertx.pgclient.impl.codec`), previously they were like that

### PR DESCRIPTION
**Pull request by BillyYccc**
Motivation:

Users can get the metadata of columns and resultset now - fixes #470.

### CODE REVIEW

**Comment by BillyYccc** [comment]
@vietj can you please take a look at this?

**Comment by vietj** [comment]
is there a pressing need for this ? I would like to study how we can do that for all clients, i.e do we need a same API for all databases ?

**Comment by BillyYccc** [comment]
That means we need to build an abstraction to describe resultset metadata but the information provided by various vendor database servers is so different that it's hard to cover all the cases using a unified API.

**Comment by aguibert** [comment]
@vietj There is now a moderate need for this item. Hibernate Reactive needs some sort of metadata similar to what JDBC metadata offers in order to perform the full set of schema management operations.

+1 that we should consider this at a generic API level though. This feature would only be useful to Hibernate Reactive if it were a generic API, in the current form (PG only) it wouldn't be easily usable by upstack libs.

**Comment by gavinking** [comment]
> Hibernate Reactive needs some sort of metadata similar to what JDBC metadata offers in order to perform the full set of schema management operations.

Well, wait. It looks like this issue refers to result set metadata. That's not what Hibernate schema management uses. What it uses is *table* metadata (information schema).

**Comment by vietj** [comment]
closing this as now we have `Columndescritpor` in master

**Pull request closed without merging**
