### PR TITLE
Prepare MS SQL Server doc before 4.1 release

### PR DESCRIPTION
**Pull request by tsegismont**

### CODE REVIEW

**Comment by gavinking** [comment]
@tsegismont does this mean it's near done?

**Comment by tsegismont** [comment]
@gavinking it depends on what you mean by done :-)

It's ready for a tech preview but there are important [limitations](https://github.com/eclipse-vertx/vertx-sql-client/blame/master/vertx-mssql-client/src/main/asciidoc/index.adoc#L16)

**Comment by gavinking** [comment]
Well I mean "done" as in "can we include it as a feature of HR yet?" :-)

**Comment by tsegismont** [comment]
@gavinking when I last tried my HR branch for Vert.x 4 + MS SQL Client, I got 77% tests passing (the rest are failed or ignored).

We can reach a better coverage by:

- updating HR to handle `NULL` parameters correctly https://vertx.io/docs/vertx-mssql-client/java/#_handling_null
- implementing batch queries in the client
- fixing #963 that breaks HR's schema setup feature

I would like to do this before Vert.x 4.1.1 is released.

This is not a direct answer to your question obviously but I hope it helps ;-)

**Comment by gavinking** [comment]
> updating HR to handle NULL parameters correctly https://vertx.io/docs/vertx-mssql-client/java/#_handling_null

Well, wouldn't it be better to fix the SQL Server client so that it behaves like the three other Vert.x drivers and doesn't have this requirement?

I mean, it's something I always *hated* in JDBC, and I was very happy to see that the Vert.x drivers did not suffer from this.

**Comment by tsegismont** [comment]
@gavinking we added it on purpose, and I can assure you we'd have avoided it if we could.

In short, SQL Server requires parameter type definitions when preparing queries. When a parameter is `null`, we can default to `nvarchar` and that works for many types... but not all (e.g. `varbinary`).

**Comment by gavinking** [comment]
Well that sucks, but OK, fine. Let me know if this does the trick: https://github.com/hibernate/hibernate-reactive/pull/845.

**Pull request merged**
