### PR TITLE
Add support for MariaDB and migrate MySQL testing to TestContainers

### LINKED ISSUE #380: MariaDB compatibility
TODO checks:

- [ ] Add testing for the MariaDB

- [ ] Fix the issues

- [ ] Connection URI scheme designator support

- [ ] Travis setup for MariaDB

- [ ] Documentation

### PR DESCRIPTION
**Pull request by BillyYccc**
Fixes #380

### CODE REVIEW

**Comment by vietj** [comment]
before accepting this PR we need to do Eclipse CQ for test containers

**Comment by BillyYccc** [comment]
@vietj how about migrating all the databases to Testcontainers some time later? Our MSSQL tests will use the that and the [embedded Postgres](https://github.com/yandex-qatools/postgresql-embedded) is not maintained anymore, if we drop using the embedded databases we will then have only one dependency on the testcontainers.

**Comment by vietj** [comment]
yes we could do that I think, it looks to work reasonably well.

**Comment by BillyYccc** [comment]
@vietj do we have a green light now on the CQ for this to be merged?

**Comment by vietj** [comment]
no we need a works-with CQ first, I will do it tomorrow

**Comment by BillyYccc** [comment]
It seems the PMC has approved the CQ request, can you please take a look at this?

**Comment by vietj** [comment]
the IP team needs to give a go as well

**Comment by BillyYccc** [comment]
Related with https://github.com/eclipse-vertx/vertx-sql-client/issues/385 and https://github.com/eclipse-vertx/vertx-sql-client/issues/386 for MySQL testing.

**Comment by BillyYccc** [comment]
I have reworked the PR and add the migrations to testcontainers for MySQL here.

**Comment by BillyYccc** [comment]
@vietj PTAL

**Pull request merged**
