### PR TITLE
DB2 client: avoid System.out logging

### LINKED ISSUE #1287: Writing "packet length: 203" to system out on connection to DB2
`io.vertx.db2client.impl.codec.InitialHandshakeCommandCodec`  is containing a `System.out.println` statement, which I'd like to remove.

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #1287

### CODE REVIEW

**Comment by tsegismont** [comment]
Thank you @Sanne , can you create a PR to `5.x` ?

**Comment by vietj** [comment]
nope 4.x

**Comment by vietj** [comment]
the CI cannot pass because the branch is not named _master_

**Comment by Sanne** [comment]
Superseded  by #1290

**Pull request closed without merging**
