### PR TITLE
Update MSSQLConnectionUriParser.java

### PR DESCRIPTION
**Pull request by Cermellus**
The MSSQLConnectionUriParser doesn't manage properly the special character ^ , so I fixed the USER_INFO_REGEX.

### CODE REVIEW

**Comment by vietj** [comment]
can you add a test @Cermellus ?

**Comment by vietj** [comment]
ping @Cermellus

**Review by tsegismont — APPROVED** [review]
LGTM, thanks @Cermellus

**Comment by tsegismont** [comment]
@vietj I've added a test in 54f0d964

**Pull request merged**
