### PR TITLE
Add support for MySQL pipelining execution

### LINKED ISSUE #861: MySQL command pipelining feature support
#### Describe the feature

Even though there is no relative official documentation stating that MySQL supports command pipelining mode which means the client sends multiple requests sequencely without waiting for the repsonse, it seems that it's possible for a client to achieve this.

We need to investigate how the pipelining works in different scenes:
* simple queries
* prepared queries(cache and one-shot)
* different command flow execution(mixing simple query + prepared query)
* utility command
* transaction

etc...

#### Use cases

I believe using pipeling mode in simple queries and prepared queries would improve performance much like what reactive postgres client ever achieved.

#### Contribution

I will investigate how this would work.

### LINKED ISSUE #873: MySQL managed one-shot prepared queries statement auto closing command should be sent before any pending commands in the queue
Motivation:
Currently MySQL auto closing command is fired after the execution is completed, this works fine because in MySQL Client the pipeling limit is only 1 and it will be sent before other pending commands, however it might cause unexpected order issues in pipeling mode which we will support later.

### PR DESCRIPTION
**Pull request by BillyYccc**
Motivation:

fixes #861, fixes #873

### CODE REVIEW

**Comment by BillyYccc** [comment]
I will create another two PRs for optional metadata and encoder rework as described in the https://github.com/eclipse-vertx/vertx-sql-client/issues/861#issuecomment-762375574.

**Comment by vietj** [comment]
should this be reviewed ?

**Comment by BillyYccc** [comment]
I will rebase on the master to adapt to the new pool implementation.

**Comment by vietj** [comment]
@BillyYccc can we review this now to be in 4.1.1 ?

**Comment by BillyYccc** [comment]
Closed with a substitution PR.

**Pull request closed without merging**
