### PR TITLE
Set SQL state when there is an exception #1385

### LINKED ISSUE #1385: DatabaseException#getSqlState is null for MS SQL Server
When a new `MSSQLException` is created, the value of DatabaseException#sqlState is always set to null.

See  https://github.com/eclipse-vertx/vertx-sql-client/blob/094817189aefce280a6bc7d391f0447fa20066d3/vertx-mssql-client/src/main/java/io/vertx/mssqlclient/MSSQLException.java#L33

The MSSQL JdbcDriver actually has a method to convert the vendor code to the sql state code: https://github.com/microsoft/mssql-jdbc/blob/ebf4d78eb985c7759cc74d4eb3c0de8cd010387d/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerException.java#L333

### PR DESCRIPTION
**Pull request by DavideD**
Fix #1385

### CODE REVIEW

**Comment by DavideD** [comment]
I think I did that in the past

**Comment by DavideD** [comment]
I've checked the website for the ECA and it seems to me that everything is fine

**Comment by tsegismont** [comment]
> I've checked the website for the ECA and it seems to me that everything is fine

Did you use the same email for your commit? The [report](https://github.com/eclipse-vertx/vertx-sql-client/pull/1386#issuecomment-1836439537) says Eclipse is not aware of your hibernate org address

**Comment by DavideD** [comment]
When I go on the website of the link, it says it is and that's valid until 2024

**Comment by DavideD** [comment]
The commit that I've sent had the verified label, though

**Pull request merged**
