### PR TITLE
Oracle: Lightweight Connection Validation

### PR DESCRIPTION
**Pull request by tsegismont**
See #1450

### CODE REVIEW

**Comment by tsegismont** [comment]
Hi @loiclefevre , I would appreciate your advice on this. Is the `SOCKET` connection validation level appropriate (non-blocking)? Or should we consider something lower, like `INBAND_DOWN` or `LOCAL`?

cc @DavideD

**Comment by gvenzl** [comment]
Hey @tsegismont,

@loiclefevre is on his well-deserved holiday, hence I'm adding @jeandelavarene to this thread to provide guidance on your question about `OracleConnection.ConnectionValidation.` and which mode to use.

**Comment by jeandelavarene** [comment]
Here is a description of the different validation modes in decreasing order of validation strength:

- "SERVER" (or "COMPLETE") makes the driver execute a basic SQL query "SELECT 'x' FROM DUAL",
- "NETWORK" makes the driver issue an OPING TTC function. This is the most lightweight roundtrip to the DB. It's the default validation mode.
- "SOCKET" makes the driver write a zero-length NS data packet on the socket that is ignored by the server. There is no guarantee that this call will always be non-blocking. It should be non-blocking in most of the cases.
- "INBAND_DOWN" makes the driver do a non-blocking socket read call on the socket
- "LOCAL" same as above
- "NONE" just checks the connection's lifecycle (variable check)

Note that, for example, a "SOCKET" validation may return a false positive (it may not always detect all socket defects). On the other hand, a "SOCKET" validation is much faster than "NETWORK". In most cases, we recommend using "SOCKET" validation at connection borrow (in UCP for example). For applications that can't tolerate an error on the connection, turning on "SERVER" or "NETWORK" would be more appropriate.

**Comment by tsegismont** [comment]
Thank you @gvenzl and @jeandelavarene 

In this part of our code we can't tolerate the driver to block (event not every time). And for the other clients (Pg, MySQL, ...etc) where Vert.x manages the connection, we only check the connection's lifecycle (variable check):

https://github.com/eclipse-vertx/vertx-sql-client/blob/ccc784a3a2b1e3f8790fb2781f14404fa83886ea/vertx-sql-client/src/main/java/io/vertx/sqlclient/impl/SocketConnectionBase.java#L160

So I think the appropriate setting is `NONE` in our case. This will provide the same experience as with other clients.

**Pull request merged**
