### PR TITLE
Build matrix for MySQL and make client compatible with MySQL 5.6

### LINKED ISSUE #354: only support Mysql great 5.7？
Hi，I found mysql client only support > 5.7, but can't  found  any describe about this.

### LINKED ISSUE #355: Build matrix for MySQL
test our `vertx-mysql-client` with MySQL 5.6, 5.7, 8.0(we can add this later).

### PR DESCRIPTION
**Pull request by BillyYccc**
This will fix #355 , fix #354 .

### CODE REVIEW

**Comment by vietj** [comment]
MySQL 5.7 does not pass is that expected ?

**Comment by BillyYccc** [comment]
looks like there's something wrong with our travis configuration.

**Comment by vietj** [comment]
can you troubleshot this on your own fork ?

**Comment by BillyYccc** [comment]
yes, I will investigate it soon.

**Pull request merged**
