### PR TITLE
During the translation, we found some format problems

### PR DESCRIPTION
**Pull request by chengenzhao**
Motivation:

Hi during the translation to Chinese, we found some looks like format problems
it should be like these:
Screen Shot 2021-02-25 at 10 12 20 AM

but actually it looks like
Screen Shot 2021-02-25 at 10 13 03 AM

I think this could because of capitalization issues e.g. NOTE: rather than Note:

### CODE REVIEW

**Comment by vietj** [comment]
can you sign the Eclipse Contributor Agreement to make this commit valid ?

**Comment by vietj** [comment]
and sign your commit

**Review by tsegismont — CHANGES_REQUESTED** [review]
Hi,

We can't change the note [_admonitions_](https://docs.asciidoctor.org/asciidoc/latest/blocks/admonitions/): in Asciidoc format these are required to be uppercase.

They are used to provide some special formatting in the output (text blocks with warning/note/etc signs)

**Comment by vietj** [comment]
@tsegismont the PR does change it to upper cases, what is wrong ?

**Review by tsegismont — APPROVED** [review]

**Comment by tsegismont** [comment]
@vietj ooops, sorry for the noise. I read the changes the wrong way...

**Comment by chengenzhao** [comment]
We have submit this PR and sign off again, so close this PR

**Pull request closed without merging**
