### PR TITLE
Transaction support for MSSQL

### LINKED ISSUE #610: [MSSQL]Transaction support
currently the sql server client does not support transactions and we should support this.

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #610

### CODE REVIEW

**Comment by tsegismont** [comment]
Not ready yet, two transaction tests are still failing

**Comment by vietj** [comment]
no worries it's a draft PR

**Review by vietj — APPROVED** [review]
but I think that @BillyYccc should check too

**Comment by tsegismont** [comment]
@vietj thanks for reviewing. I believe Billy is currently busy. Given the project is still in early stage, it is fine to merge and revisit later.

**Pull request merged**
