### PR TITLE
Fix ambiguos method call error in IDE

### PR DESCRIPTION
**Pull request by DavideD**
Similar to https://github.com/eclipse-vertx/vertx-sql-client/pull/888
But for `master`.

Resolves an error with Eclipse.

### CODE REVIEW

**Review by vietj — CHANGES_REQUESTED** [review]
can you rebase this PR to have CI that passes ?

**Comment by DavideD** [comment]
I've rebased this issue but I'm not sure if it's still needed

**Comment by vietj** [comment]
why?

**Comment by DavideD** [comment]
> can you rebase this PR to have CI that passes ?

I've only noticed this comment yesterday. This PR is similar to #888 and it's still open.
I haven't tried importing the project in Eclipse for a while so if you think this change is not necessary, feel free to close this PR.

**Comment by DavideD** [comment]
I'm going to close this one. I haven't tested eclipse in a while and I'm not even sure it's worth fixing anyway (the code works). Sorry, about the noise

**Pull request closed without merging**
