### PR TITLE
Implement Oracle binary types encoding and decoding

### LINKED ISSUE #1085: Filtering on column of type raw throws an exception in Oracle
This is the exception:
```
ORA-00932: inconsistent datatypes: expected - got BLOB
```
It happens with the following query (for example) passing a parameter of type `Buffer`:
```
select * from UUIDEntity where id in (?,?)
```
where the table `UUIDEntity` is created with:
```
create table UUIDEntity (id raw(255) not null, name varchar2(255 char), primary key (id))
```

Note that the error happens even if the field is not a key of the table. Everything works fine if it's an insert query.

I've created a testcase here:  https://github.com/DavideD/vertx-sql-client/commit/b72733af9507a5f197cd1bfed6b11e95afd6310e

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #1085

### CODE REVIEW

**Comment by tsegismont** [comment]
@DavideD would you mind reviewing this one please?

**Comment by DavideD** [comment]
Testing...

**Comment by DavideD** [comment]
That specific issue is fixed, but something else fails when I switch from `4.3.0` to `4.3.1-SNAPSHOT`. 
I'm trying to figure out what's going on

**Comment by DavideD** [comment]
This solution doesn't really work for us.

The problem is that a value of type `blob` in the db is returned as `io.vertx.oracleclient.data.Blob` (in `4.3.0` the value is returned as `byte[]`).
That class only exists in the `vertx-oracle-client` (we might not have it on the classpath.
Can't you return the value as `byte[]` like in `4.3.0`?

**Comment by DavideD** [comment]
I don't think so.

We don't know in advance what value will be returned by a query, just that it's something that can be converted to a `java.sql.Blob`. This means that other dbs might return a `byte[]` or  a `String` and if we call `getBuffer`on one of those fields we have an exception (I think).

I would need to run more tests to be more precise.
But this is our implementation at the moment:
```
       private io.vertx.sqlclient.Row row;

	@Override
	public Blob getBlob(String columnLabel) {
		final Object value = row.getValue( columnLabel );
		wasNull = value == null;
		if ( wasNull ) {
			return null;
		}

		if ( value instanceof Buffer ) {
			return BlobProxy.generateProxy( ( (Buffer) value ).getBytes() );
		}
		if ( value instanceof String ) {
			return BlobProxy.generateProxy( ( (String) value ).getBytes() );
		}
		if ( value instanceof byte[] ) {
			return BlobProxy.generateProxy( (byte[]) value );
		}

		throw new IllegalArgumentException( "Unexpected type: " + value.getClass() + " for column " + columnLabel );
	}
```

This is the same code for all dbs.

**Comment by DavideD** [comment]
Atually, it might work, let me try

**Comment by tsegismont** [comment]
@DavideD I changed the implementation, `io.vertx.oracleclient.data.Blob` will be required only when inserting/filtering.

I verified that HR test suite passes with these changes.

**Comment by DavideD** [comment]
OK, thanks

**Pull request merged**
