### PR TITLE
MySQL documentation

### PR DESCRIPTION
**Pull request by BillyYccc**
Initial work for MySQL documentation, related to #317.

### CODE REVIEW

**Comment by BillyYccc** [comment]
@vietj I think we may not need a dedicated section for `SqlClient`, we can just build paralled documentation for only MySQL and PostgreSQL because I find there is not too much things which can be shared between them.

**Comment by vietj** [comment]
I believe we should have a common section like there is with vertx-sql-common

**Comment by vietj** [comment]
then we can include this section (and repeat it) in all implementations using asciidoc include

**Comment by vietj** [comment]
I believe that an example should take a pool or connection as input and then any example that does not have to use specific Pg / MySQL prefixed implementation can be shared:

```
public void example(SqlConnection conn) {
   ...
}
```

**Comment by BillyYccc** [comment]
ok, shall we first get this into merged and then see what can be extracted to the common section of documentation?

**Comment by vietj** [comment]
I have no strong opinion about this @BillyYccc , up to you

**Comment by BillyYccc** [comment]
I have created a ticket for this, let's first merge this and then solve #319 later.

**Pull request merged**
