### PR TITLE
Check context when closing cursor

### PR DESCRIPTION
**Pull request by rasmusfaber**
Motivation:

Fix for https://github.com/eclipse-vertx/vertx-sql-client/issues/967

Conformance:

Check.

### CODE REVIEW

**Comment by vietj** [comment]
for master this is likely not the right fix because of the way we handle communication between the client and the internal socket

**Comment by vietj** [comment]
do you have a test for this issue ?

**Comment by rasmusfaber** [comment]
Yes, sorry. I can't reproduce it on master after all. It looks like the issues were fixed with https://github.com/eclipse-vertx/vertx-sql-client/commit/9d33256cc1b49c5c9a0cb794eebf1a3cb8991fe6#diff-0de8b326c2028289e736255bc6868132071c24d1df94694cd700f63bde274ab2R128

**Comment by vietj** [comment]
@rasmusfaber did you check whether the issue happens with master ? normally master handles correctly different contexts

**Pull request closed without merging**
